[env:tinylora_v2]
extends = esp32c3_base
board = esp32-c3-devkitm-1
build_flags = 
  ${esp32_base.build_flags}
  -D TINYLORA_V2
  -I variants/esp32c3/heltec_esp32c3
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=0

[env:tinylora_v2_29s]
extends = esp32c3_base
board = esp32-c3-devkitm-1
build_flags = 
  ${esp32_base.build_flags}
  -D TINYLORA_V2
  -I variants/esp32c3/heltec_esp32c3
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=0
  -D SX126X_MAX_POWER=3

[env:tinylora_v3_gps_29s]
extends = esp32c3_base
board = esp32-c3-devkitm-1
build_flags = 
  ${esp32_base.build_flags}
  -D TINYLORA_V3
  -D TINYLORA_V3_GPS
  -I variants/esp32c3/tinylora
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D SX126X_MAX_POWER=3

[env:tinylora_v3_gps_22s]
extends = esp32c3_base
board = esp32-c3-devkitm-1
build_flags = 
  ${esp32_base.build_flags}
  -D TINYLORA_V3
  -D TINYLORA_V3_GPS
  -I variants/esp32c3/tinylora
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D SX126X_MAX_POWER=22

[env:tinylora_v3_i2c_29s]
extends = esp32c3_base
board = esp32-c3-devkitm-1
build_flags = 
  ${esp32_base.build_flags}
  -D TINYLORA_V3
  -D TINYLORA_V3_I2C
  -I variants/esp32c3/tinylora
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D SX126X_MAX_POWER=3

[env:tinylora_v3_i2c_22s]
extends = esp32c3_base
board = esp32-c3-devkitm-1
build_flags = 
  ${esp32_base.build_flags}
  -D TINYLORA_V3
  -D TINYLORA_V3_I2C
  -I variants/esp32c3/tinylora
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D SX126X_MAX_POWER=22

[env:tinylora_v4]
extends = esp32c3_base
board = esp32-c3-devkitm-1
build_flags = 
  ${esp32_base.build_flags}
  -D TINYLORA_V4
  -I variants/esp32c3/tinylora
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

